/* Dependency-free preview state/DOM-contract regression tests. Run: node tests/test_preview.cjs */
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const html=fs.readFileSync(path.join(__dirname,'../tools/preview/index.html'),'utf8');
assert.equal((html.match(/<script>/g)||[]).length,2,'one executable script plus harmless escaped test text');
assert.equal((html.match(/<\/script>/g)||[]).length,1,'only one HTML closing script');
assert(!/(?:src|href)=["']https?:/i.test(html));
assert(html.includes("connect-src 'none'"));
const script=html.match(/<script>([\s\S]*?)<\/script>/)[1];
const nodes=new Map(),listeners={},saved={};
const doc={documentElement:{dataset:{},lang:''},activeElement:null,addEventListener(k,fn){listeners[k]=fn;},getElementById(id){if(!nodes.has(id))nodes.set(id,{id,hidden:id==='modal-layer',innerHTML:'',textContent:'',value:'',dataset:{},style:{},options:[{},{}],isConnected:true,addEventListener(k,fn){this[k]=fn;},focus(){doc.activeElement=this;},querySelector(){return this;},setPointerCapture(){},getBoundingClientRect(){return {left:0,top:0,width:600,height:180};}});return nodes.get(id);}};
const context={document:doc,window:{},localStorage:{getItem(k){return saved[k]||null;},setItem(k,v){saved[k]=v;}},console};
vm.runInNewContext(script,context,{filename:'preview-inline.js'});
const api=context.window.MixPreview,s=api.state;
let count=0;function check(name,fn){fn();count++;console.log('PASS',name);}
check('five pages in both languages, all four themes and two scenarios',()=>{for(const scenario of ['offline','mock'])for(const theme of ['graphite','paper','midnight','ember'])for(const lang of ['en','zh'])for(const page of ['home','power','terminal','device','settings']){Object.assign(s,{scenario,theme,lang,page});api.render();assert(nodes.get('app').innerHTML.length>100);assert.equal(doc.documentElement.dataset.theme,theme);assert.equal((nodes.get('nav').innerHTML.match(/data-page=/g)||[]).length,5);}});
check('offline session refuses connection and unknown telemetry stays unknown',()=>{Object.assign(s,{scenario:'offline',session:false,lang:'en',page:'home'});api.dispatch('open-terminal');assert.equal(s.session,false);s.page='power';api.render();assert(nodes.get('app').innerHTML.includes('Unavailable'));assert(!nodes.get('app').innerHTML.includes('<polyline'));assert(nodes.get('app').innerHTML.includes('Calibration has not been verified'));});
check('mock terminal stays connected across page changes',()=>{s.scenario='mock';api.dispatch('open-session');assert(s.session);s.page='home';api.feed('background output');api.render();assert(s.session);assert(s.history.includes('background output'));});
check('fixed 80 columns, CJK width two, exactly 28 rows',()=>{const cells=api.terminalCells('A中文B');assert.equal(cells.reduce((n,c)=>n+c.width,0),80);assert.equal(cells[1].width,2);assert.equal(api.terminalCells('A'.repeat(79)+'中').filter(c=>c.width===2).length,0);assert.equal(api.terminalRows().length,28);});
check('100 history lines plus 28 screen lines, bounded scroll',()=>{for(let i=0;i<200;i++)api.feed('line '+i);assert.equal(s.history.length,128);for(let i=0;i<20;i++)api.dispatch('older');assert.equal(s.scroll,100);assert.equal(api.terminalRows().length,28);api.dispatch('live');assert.equal(s.scroll,0);});
check('untrusted output is escaped and cannot start or confirm actions',()=>{s.page='terminal';const n=s.actions.length;api.feed('<img src=x onerror=alert(1)>\n\x1b[confirm]\r\nYES');api.render();assert.equal(s.actions.length,n);assert.equal(s.modal,null);assert(nodes.get('app').innerHTML.includes('&lt;'));assert(!nodes.get('app').innerHTML.includes('<img src=x'));api.request('update');api.feed('Enter YES\n');assert.equal(s.modal,'update');assert.equal(s.actions.length,n);api.resolve(false);assert.equal(s.actions.at(-1).accepted,false);});
check('independent modal requires local Enter and Escape rejects',()=>{api.request('maintenance');assert.equal(s.job,false);assert.equal(nodes.get('app').inert,true);let prevented=false;listeners.keydown({key:'Escape',preventDefault(){prevented=true;},stopPropagation(){}});assert(prevented);assert.equal(s.job,false);api.request('maintenance');listeners.keydown({key:'Enter',preventDefault(){},stopPropagation(){}});assert.equal(s.job,true);assert.equal(s.modal,null);assert.equal(nodes.get('app').inert,false);api.request('cancel-job');api.resolve(true);assert.equal(s.job,false);});
check('modal blocks navigation and duplicate requests',()=>{api.request('reset');api.request('maintenance');assert.equal(s.modal,'reset');const p=s.page;api.dispatch('open-terminal');assert.equal(s.page,p);api.resolve(false);});
check('single pointer rejects second finger and releases on cancel',()=>{s.page='device';s.touch=true;api.render();const pad=nodes.get('touch-pad');pad.onpointerdown({pointerId:1,clientX:20,clientY:30});assert.equal(s.pointer,1);pad.onpointerdown({pointerId:2,clientX:40,clientY:50});assert.equal(s.pointer,1);pad.onpointercancel({pointerId:1});assert.equal(s.pointer,null);assert(nodes.get('touch-coordinates').textContent.includes('UP'));});
check('theme and language prefs are persisted and validated',()=>{api.dispatch('theme-ember');api.dispatch('lang-zh');assert.deepEqual(JSON.parse(saved['mixui-preview']),{theme:'ember',lang:'zh'});api.dispatch('theme-invalid');assert.equal(s.theme,'ember');});
check('brightness clamps, keyboard steps, reset confirms locally',()=>{listeners.input({target:{id:'brightness',value:'500'}});assert.equal(s.brightness,100);for(let i=0;i<4;i++)api.dispatch('kbd');assert.equal(s.kbd,0);s.touch=true;api.request('reset');api.resolve(true);assert.equal(s.touch,false);});
check('incoming output preserves the scrolled history position',()=>{s.history=[];s.scroll=0;for(let i=0;i<70;i++)api.feed('stable '+i);api.dispatch('older');const first=api.terminalRows()[0];api.feed('new background line');assert.equal(api.terminalRows()[0],first);api.dispatch('live');});
check('confirmed mock maintenance progresses to completion',()=>{api.request('maintenance');api.resolve(true);for(let i=0;i<4;i++)api.dispatch('advance-job');assert.equal(s.jobPercent,100);assert.equal(s.job,false);assert(s.notice.length>0);});
console.log(`${count} preview regression groups passed (80 page/theme/language/scenario renders).`);
