"""Official 60px navigation A8 assets, without a device or firmware compiler.

Default tests validate the checked-in C arrays and fixed source/axis policy.
MIXOS_TEST_MATERIAL_ICONS=1 also regenerates from the actual pinned Google
TTF; a path value selects a byte-identical TTF elsewhere. Prepare navigation
artifacts with build_material_nav_icons.py first. The existing sports_esports
builder supplies an independent per-glyph oracle for pipeline consistency.
"""
from __future__ import annotations

import copy
import importlib.util
import io
import json
import os
from pathlib import Path
import re
import tempfile
import unittest
from unittest import mock

from fontTools.ttLib import TTFont
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]


def load_tool(name: str):
    spec = importlib.util.spec_from_file_location("nav_test_" + name, ROOT / "tools" / (name + ".py"))
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


nav = load_tool("build_material_nav_icons")
game = load_tool("build_material_icon")
GOLDEN = {
    "arrow_back": {"size": (39, 38), "bytes": 1482, "glyph_id": 3129,
                   "bbox": [11, 0, 50, 38], "origin": [11, 17], "levels": 30,
                   "sha256": "6560881b2fed55c14d3666456b5f13ac6bac5cd55db28d9e69a85cbb1b4742de"},
    "home": {"size": (40, 45), "bytes": 1800, "glyph_id": 3743,
             "bbox": [10, 0, 50, 45], "origin": [10, 14], "levels": 57,
             "sha256": "b8fc4edb33444759ee0e8a4308ea0e8e57eb42cb8963d9e2657365de6c58636c"},
    "settings": {"size": (48, 52), "bytes": 2496, "glyph_id": 5937,
                 "bbox": [6, 0, 54, 52], "origin": [6, 10], "levels": 153,
                 "sha256": "70534bd70699e3a8621df0d4e0d939c177017e0ce21d561438ce98fc1d626e2f"},
}


def read_header(data: bytes) -> dict[str, tuple[tuple[int, int], bytes]]:
    text = data.decode("ascii")
    if re.findall(r"^#define MIX_NAV_ICON_SIZE (\d+)$", text, re.MULTILINE) != ["60"]:
        raise AssertionError("one common 60px em size is required")
    result = {}
    for name in nav.GLYPHS:
        macro = "MIX_NAV_" + name.upper()
        dimensions = {key: int(value) for key, value in re.findall(
            rf"^#define {macro}_(WIDTH|HEIGHT) (\d+)$", text, re.MULTILINE)}
        if set(dimensions) != {"WIDTH", "HEIGHT"}:
            raise AssertionError("missing public dimensions: " + name)
        body = re.search(rf"static const uint8_t mix_nav_{name}_alpha\[{macro}_WIDTH \* {macro}_HEIGHT\] = \{{(.*?)\}};",
                         text, re.DOTALL)
        if body is None:
            raise AssertionError("missing exact public A8 declaration: " + name)
        if re.sub(r"0x[0-9a-f]{2}|[\s,]", "", body[1]):
            raise AssertionError("unexpected initializer content or out-of-range A8 value")
        alpha = bytes(int(value, 16) for value in re.findall(r"0x[0-9a-f]{2}", body[1]))
        result[name] = ((dimensions["WIDTH"], dimensions["HEIGHT"]), alpha)
    if len(re.findall(r"static const uint8_t", text)) != 3:
        raise AssertionError("expected exactly three navigation arrays")
    return result


class NavigationHeaderTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.header = nav.DEFAULT_HEADER.read_bytes()
        cls.text = cls.header.decode("ascii")
        cls.glyphs = read_header(cls.header)

    def test_exact_public_interface_size_and_golden_coverage(self):
        self.assertIn("#ifndef MIX_NAV_ICONS_H", self.text)
        self.assertIn("#include <stdint.h>", self.text)
        self.assertEqual(nav.GLYPHS, {"arrow_back": 0xE5C4, "home": 0xE88A, "settings": 0xE8B8})
        for name, (size, alpha) in self.glyphs.items():
            with self.subTest(glyph=name):
                golden = GOLDEN[name]
                self.assertEqual(size, golden["size"])
                self.assertEqual(len(alpha), size[0] * size[1])
                self.assertEqual(len(alpha), golden["bytes"])
                self.assertEqual(nav.digest(alpha), golden["sha256"])
                self.assertIn("alphaSHA256: " + nav.digest(alpha), self.text)
                self.assertEqual(len(set(alpha)), golden["levels"])
                self.assertIn(0, alpha)
                self.assertIn(255, alpha)
                nav.validate_alpha(alpha, *size)
        self.assertEqual(sum(len(alpha) for _, alpha in self.glyphs.values()), 5778)

    def test_header_preserves_source_license_and_crop_metadata(self):
        for required in (
            "Google Material Symbols Rounded", "Copyright 2026 Google LLC.",
            "SPDX-License-Identifier: Apache-2.0", nav.LICENSE_URL, nav.FONT_URL,
            "sourcefontSHA256: " + nav.SOURCE_SHA256,
            "Fixed axes: FILL0/wght400/GRAD0/opsz24 (identical to sports_esports)",
            "Generated by tools/build_material_nav_icons.py v" + nav.GENERATOR_VERSION,
            "Generator SHA256: " + nav.digest((ROOT / nav.GENERATOR).read_bytes()),
            "Raster em size: 60px; UPEM: 960 -> 1000", "Ink crop only",
            "Pillow 11.2.1; FreeType 2.13.3; BASIC", "fontTools: 4.60.1",
        ):
            with self.subTest(required=required):
                self.assertIn(required, self.text)
        for name, codepoint in nav.GLYPHS.items():
            self.assertIn(f"Official glyphname: {name}; codepoint: U+{codepoint:04X}", self.text)
            self.assertIn(f"Ink bbox in FreeType mask: {GOLDEN[name]['bbox']}", self.text)
            self.assertIn(f"Ink origin relative to left ascender: {GOLDEN[name]['origin']}", self.text)

    def test_same_official_source_and_axes_as_game_and_font_builder(self):
        for attribute in ("AXES", "SOURCE_SHA256", "SOURCE_UPEM", "MISANS_UPEM", "FAMILY",
                          "FIXED_SFNT_TIME", "UPSTREAM_COMMIT", "FONT_URL", "LICENSE_URL", "LICENSE_SHA256"):
            with self.subTest(attribute=attribute):
                self.assertEqual(getattr(nav, attribute), getattr(game, attribute))
        self.assertEqual(nav.AXES, load_tool("build_font").ICON_INSTANCE)
        self.assertEqual(nav.SIZE, 60)
        self.assertEqual(game.SIZE, 70)

    def test_alpha_validation_rejects_invalid_coverage(self):
        for data, width, height, message in (
            (b"\x80", 2, 1, "length"), (b"\0", 1, 1, "empty"),
            (b"\0\xff", 2, 1, "antialiasing"), (b"\0\x80\0", 3, 1, "cropped"),
            (b"\x80" * 61, 61, 1, "dimensions"), (b"", 0, 0, "dimensions"),
        ):
            with self.subTest(message=message), self.assertRaisesRegex(nav.MaterialNavIconError, message):
                nav.validate_alpha(data, width, height)

    def test_aliases_are_rejected_before_writing_source(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            source = root / "source.ttf"
            source.write_bytes(b"read-only test sentinel, not a font")
            before = source.read_bytes()
            for header, artifacts in ((source, root / "artifacts"), (root / "result.h", source),
                                      (root / "arrow_back-60.a8", root)):
                with self.subTest(header=header), self.assertRaisesRegex(nav.MaterialNavIconError, "alias"):
                    nav.build(source, header, artifacts)
            with self.assertRaisesRegex(nav.MaterialNavIconError, "alias"):
                nav.build(source, root / "result.h", root, license_source=root / nav.LICENSE_FILE)
            self.assertEqual(source.read_bytes(), before)

    def test_wrong_source_is_rejected_before_network_or_publication(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            source, header = root / "source.ttf", root / "result.h"
            source.write_bytes(b"not the pinned official font")
            header.write_bytes(b"previous header")
            with mock.patch.object(nav.urllib.request, "urlopen") as network:
                with self.assertRaisesRegex(nav.MaterialNavIconError, "sourcefontSHA256"):
                    nav.build(source, header, root / "artifacts", fetch_license=True)
                network.assert_not_called()
            self.assertEqual(header.read_bytes(), b"previous header")
            self.assertFalse((root / "artifacts").exists())

    def test_check_forbids_license_bootstrap_and_network_modes(self):
        for kwargs in ({"fetch_license": True}, {"license_source": Path("existing-license.txt")}):
            with self.subTest(kwargs=kwargs), self.assertRaisesRegex(nav.MaterialNavIconError, "read-only/offline"):
                nav.build(check=True, **kwargs)


@unittest.skipUnless(os.environ.get("MIXOS_TEST_MATERIAL_ICONS"),
                     "set MIXOS_TEST_MATERIAL_ICONS=1 (or source TTF path) for real-source regeneration")
class RealNavigationIconTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        setting = os.environ["MIXOS_TEST_MATERIAL_ICONS"]
        cls.source = nav.DEFAULT_SOURCE if setting == "1" else Path(setting)
        cls.source_data = cls.source.read_bytes()
        protected = [cls.source, game.DEFAULT_HEADER, ROOT / game.GENERATOR,
                     *(ROOT / "build/font").glob("*.ttf")]
        cls.protected_files = {path: (nav.digest(path.read_bytes()), path.stat().st_mtime_ns) for path in protected}
        cls.alphas, cls.record = nav.rasterize(cls.source_data)
        cls.license_data = (nav.DEFAULT_ARTIFACTS / nav.LICENSE_FILE).read_bytes()

    def test_actual_cmap_names_ids_and_pinned_google_source(self):
        self.assertEqual(nav.digest(self.source_data), nav.SOURCE_SHA256)
        with TTFont(io.BytesIO(self.source_data), recalcTimestamp=False) as font:
            source = nav.validate_font(font)
            self.assertEqual(source["family"], "Material Symbols Rounded")
            self.assertEqual(source["source_units_per_em"], 960)
            for name, codepoint in nav.GLYPHS.items():
                with self.subTest(glyph=name):
                    self.assertEqual(font.getBestCmap()[codepoint], name)
                    self.assertEqual(source["glyphs"][name]["source_glyph_id"], GOLDEN[name]["glyph_id"])
                    self.assertEqual(self.record["glyphs"][name]["ink_bbox_in_mask_px"], GOLDEN[name]["bbox"])
                    self.assertEqual(self.record["glyphs"][name]["ink_origin_left_ascender_px"], GOLDEN[name]["origin"])

    def test_missing_or_conflicting_cmap_is_rejected(self):
        for name, codepoint in nav.GLYPHS.items():
            with self.subTest(glyph=name), TTFont(io.BytesIO(self.source_data), recalcTimestamp=False) as font:
                best = font.getBestCmap()
                other = next(table for table in font["cmap"].tables
                             if table.isUnicode() and table.format in (4, 12) and table.cmap is not best)
                original = other.cmap
                other.cmap = dict(original)
                other.cmap[codepoint] = ".notdef"
                with self.assertRaisesRegex(nav.MaterialNavIconError, "subtables disagree"):
                    nav.validate_font(font)
                other.cmap = original
                for table in font["cmap"].tables:
                    if table.isUnicode() and table.format in (4, 12):
                        table.cmap[codepoint] = ".notdef"
                with self.assertRaisesRegex(nav.MaterialNavIconError, "actual cmap"):
                    nav.validate_font(font)

    def test_header_raw_alpha_png_manifest_license_and_readonly_check(self):
        paths = [nav.DEFAULT_HEADER, *(nav.DEFAULT_ARTIFACTS / name for name in nav.artifact_names())]
        before = {path: (path.read_bytes(), path.stat().st_mtime_ns) for path in paths}
        with mock.patch.object(nav.urllib.request, "urlopen", side_effect=AssertionError("check must be offline")):
            checked = nav.build(self.source, check=True)
        self.assertEqual(checked, json.loads((nav.DEFAULT_ARTIFACTS / nav.MANIFEST_FILE).read_bytes()))
        self.assertEqual(nav.render_header(self.alphas, self.record), nav.DEFAULT_HEADER.read_bytes())
        header_glyphs = read_header(nav.DEFAULT_HEADER.read_bytes())
        for name, alpha in self.alphas.items():
            with self.subTest(glyph=name):
                self.assertEqual(alpha, (nav.DEFAULT_ARTIFACTS / f"{name}-60.a8").read_bytes())
                self.assertEqual(header_glyphs[name], (GOLDEN[name]["size"], alpha))
                self.assertEqual(nav.digest(alpha), GOLDEN[name]["sha256"])
                with Image.open(nav.DEFAULT_ARTIFACTS / f"{name}-60.png") as png:
                    self.assertEqual(png.mode, "L")
                    self.assertEqual(png.size, GOLDEN[name]["size"])
                    self.assertEqual(png.tobytes(), alpha)
        self.assertEqual(nav.digest(self.license_data), nav.LICENSE_SHA256)
        self.assertIn(b"Apache License", self.license_data)
        self.assertEqual(before, {path: (path.read_bytes(), path.stat().st_mtime_ns) for path in before})

    def test_existing_game_pipeline_produces_identical_navigation_coverage(self):
        # Use the unmodified game's real instancing/FreeType implementation as
        # an independent oracle. Only select each official glyph and 60px em.
        for name, codepoint in nav.GLYPHS.items():
            with self.subTest(glyph=name), mock.patch.multiple(game, SIZE=60, CODEPOINT=codepoint, GLYPH_NAME=name):
                alpha, record = game.rasterize(self.source_data)
                self.assertEqual(alpha, self.alphas[name])
                self.assertEqual(record["bitmap"], self.record["glyphs"][name]["bitmap"])
                self.assertEqual(record["rasterizer"]["ink_bbox_in_mask_px"], GOLDEN[name]["bbox"])
        self.assertEqual(game.SIZE, 70)
        self.assertEqual(game.CODEPOINT, 0xEA28)
        self.assertEqual(game.GLYPH_NAME, "sports_esports")

    def test_repeatable_with_different_clock(self):
        with mock.patch("fontTools.ttLib.tables._h_e_a_d.timestampNow", return_value=4100000000):
            alphas, record = nav.rasterize(self.source_data)
        self.assertEqual(alphas, self.alphas)
        self.assertEqual(record, self.record)
        self.assertEqual(nav.render_header(alphas, record), nav.DEFAULT_HEADER.read_bytes())

    def test_check_detects_every_stale_or_missing_output_without_repair(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            artifacts, header = root / "artifacts", root / "mix_nav_icons.h"
            artifacts.mkdir()
            (artifacts / nav.LICENSE_FILE).write_bytes(self.license_data)
            # Reuse a genuinely rasterized result; the offline regeneration
            # test above checks the unmocked implementation against all bytes.
            with mock.patch.object(nav, "rasterize", side_effect=lambda data: (self.alphas, copy.deepcopy(self.record))):
                nav.build(self.source, header, artifacts)
                paths = [header, *(artifacts / name for name in nav.artifact_names() if name != nav.LICENSE_FILE)]
                for path in paths:
                    original = path.read_bytes()
                    path.write_bytes(original + b"stale")
                    with self.subTest(output=path.name), self.assertRaisesRegex(nav.MaterialNavIconError, "differ"):
                        nav.build(self.source, header, artifacts, check=True)
                    self.assertEqual(path.read_bytes(), original + b"stale")
                    path.unlink()
                    with self.subTest(missing=path.name), self.assertRaisesRegex(nav.MaterialNavIconError, "missing"):
                        nav.build(self.source, header, artifacts, check=True)
                    self.assertFalse(path.exists())
                    path.write_bytes(original)

    def test_corrupt_license_fails_before_rasterization_or_publication(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            (root / nav.LICENSE_FILE).write_bytes(self.license_data + b"changed")
            with mock.patch.object(nav, "rasterize") as rasterize:
                with self.assertRaisesRegex(nav.MaterialNavIconError, "license SHA256 mismatch"):
                    nav.build(self.source, root / "icon.h", root, check=True)
                rasterize.assert_not_called()
            self.assertFalse((root / "icon.h").exists())

    def test_render_rejects_missing_glyph_or_changed_coverage(self):
        missing = dict(self.alphas)
        del missing["home"]
        with self.assertRaisesRegex(nav.MaterialNavIconError, "all three"):
            nav.render_header(missing, self.record)
        record = copy.deepcopy(self.record)
        record["glyphs"]["home"]["bitmap"]["alphaSHA256"] = "wrong digest"
        with self.assertRaisesRegex(nav.MaterialNavIconError, "alphaSHA256"):
            nav.render_header(self.alphas, record)

    def test_zz_source_text_fonts_and_existing_game_files_remain_unchanged(self):
        self.assertEqual(self.protected_files, {
            path: (nav.digest(path.read_bytes()), path.stat().st_mtime_ns) for path in self.protected_files})


if __name__ == "__main__":
    unittest.main()
