"""Official Material Symbols A8 resource tests, without any device or compiler.

Default tests inspect the checked-in header and generator contract. Real font
regeneration is opt-in: MIXOS_TEST_MATERIAL_ICONS=1 uses the default source;
a path value selects an identical copy of the pinned official source font.
Prepare the generated artifacts/license with build_material_icon.py first.
No synthetic or hand-drawn icon is used as production input or test oracle.
"""
from __future__ import annotations

import copy
import importlib.util
import io
import json
import os
from pathlib import Path
import re
import tempfile
import unittest
from unittest import mock

from fontTools.ttLib import TTFont
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
SPEC = importlib.util.spec_from_file_location("build_material_icon", ROOT / "tools/build_material_icon.py")
icon = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(icon)
GOLDEN_ALPHA_SHA256 = "5712616bf0a0af45e1f513187cd98bc8db06588565fc739b9ba157c5260a8a9f"


def read_header(data: bytes) -> tuple[dict[str, int], bytes]:
    text = data.decode("ascii")
    dimensions = {key: int(value) for key, value in re.findall(
        r"^#define MIX_GAME_ICON_(SIZE|WIDTH|HEIGHT) (\d+)$", text, re.MULTILINE)}
    body = re.search(r"static const uint8_t mix_game_icon_alpha\[MIX_GAME_ICON_WIDTH \* MIX_GAME_ICON_HEIGHT\] = \{(.*?)\};",
                     text, re.DOTALL)
    if body is None:
        raise AssertionError("missing exact public A8 declaration")
    values = re.findall(r"0x[0-9a-f]{2}", body[1])
    if re.sub(r"0x[0-9a-f]{2}|[\s,]", "", body[1]):
        raise AssertionError("unexpected initializer content or out-of-range A8 value")
    return dimensions, bytes(int(value, 16) for value in values)


class HeaderResourceTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.header = icon.DEFAULT_HEADER.read_bytes()
        cls.text = cls.header.decode("ascii")
        cls.dimensions, cls.alpha = read_header(cls.header)

    def test_public_header_interface_and_exact_dimensions(self):
        self.assertIn("#include <stdint.h>", self.text)
        self.assertIn("#ifndef MIX_GAME_ICON_H", self.text)
        self.assertEqual(self.dimensions, {"SIZE": 70, "WIDTH": 60, "HEIGHT": 42})
        self.assertEqual(len(self.alpha), self.dimensions["WIDTH"] * self.dimensions["HEIGHT"])
        self.assertEqual(len(self.alpha), 2520)

    def test_metadata_identifies_official_source_and_fixed_instance(self):
        for required in (
            "Official glyphname: sports_esports; codepoint: U+EA28",
            "Google Material Symbols Rounded", "Copyright 2026 Google LLC.",
            "SPDX-License-Identifier: Apache-2.0", icon.LICENSE_URL, icon.FONT_URL,
            "Fixed axes: FILL0/wght400/GRAD0/opsz24",
            "sourcefontSHA256: " + icon.SOURCE_SHA256,
            "Generated by tools/build_material_icon.py v" + icon.GENERATOR_VERSION,
            "fontTools:", "Rasterizer: Pillow", "FreeType", "BASIC",
            "Raster em size: 70px; UPEM: 960 -> 1000", "Ink crop only",
        ):
            with self.subTest(required=required):
                self.assertIn(required, self.text)
        self.assertIn("Generator SHA256: " + icon.digest((ROOT / icon.GENERATOR).read_bytes()), self.text)

    def test_alpha_preserves_coverage_and_matches_declared_digest(self):
        icon.validate_alpha(self.alpha, self.dimensions["WIDTH"], self.dimensions["HEIGHT"])
        self.assertIn(0, self.alpha)
        self.assertIn(255, self.alpha)
        self.assertTrue(any(0 < value < 255 for value in self.alpha))
        self.assertEqual(len(set(self.alpha)), 168)
        self.assertEqual(icon.digest(self.alpha), GOLDEN_ALPHA_SHA256)
        self.assertIn("alphaSHA256: " + icon.digest(self.alpha), self.text)

    def test_axes_stay_identical_to_existing_merge_icons_policy(self):
        spec = importlib.util.spec_from_file_location("material_test_build_font", ROOT / "tools/build_font.py")
        text_builder = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(text_builder)
        self.assertEqual(icon.AXES, text_builder.ICON_INSTANCE)
        self.assertEqual(icon.SOURCE_UPEM, 960)
        self.assertEqual(icon.MISANS_UPEM, 1000)

    def test_alpha_validation_rejects_bad_length_empty_binary_or_untrimmed_ink(self):
        for data, width, height, message in (
            (b"\x80", 2, 1, "length"),
            (b"\0", 1, 1, "empty"),
            (b"\0\xff", 2, 1, "antialiasing"),
            (b"\0\x80\0", 3, 1, "cropped"),
            (b"\x80" * 71, 71, 1, "dimensions"),
        ):
            with self.subTest(message=message), self.assertRaisesRegex(icon.MaterialIconError, message):
                icon.validate_alpha(data, width, height)

    def test_source_output_aliases_are_rejected_without_writing(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            source = root / "source.ttf"
            source.write_bytes(b"read-only test sentinel, not a font")
            before = source.read_bytes()
            with self.assertRaisesRegex(icon.MaterialIconError, "alias"):
                icon.build(source, source, root / "artifacts")
            with self.assertRaisesRegex(icon.MaterialIconError, "alias"):
                icon.build(source, root / "result.h", source)
            self.assertEqual(source.read_bytes(), before)

    def test_unknown_source_is_rejected_before_network_or_publication(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            source, header = root / "source.ttf", root / "old.h"
            source.write_bytes(b"not the pinned official font")
            header.write_bytes(b"previous result")
            with mock.patch.object(icon.urllib.request, "urlopen") as network:
                with self.assertRaisesRegex(icon.MaterialIconError, "sourcefontSHA256"):
                    icon.build(source, header, root / "artifacts", fetch_license=True)
                network.assert_not_called()
            self.assertEqual(header.read_bytes(), b"previous result")
            self.assertEqual(source.read_bytes(), b"not the pinned official font")
            self.assertFalse((root / "artifacts").exists())

    def test_check_forbids_download_mode(self):
        with self.assertRaisesRegex(icon.MaterialIconError, "read-only/offline"):
            icon.build(check=True, fetch_license=True)


@unittest.skipUnless(os.environ.get("MIXOS_TEST_MATERIAL_ICONS"),
                     "set MIXOS_TEST_MATERIAL_ICONS=1 (or source TTF path) for real-source regeneration")
class RealMaterialIconTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        setting = os.environ["MIXOS_TEST_MATERIAL_ICONS"]
        cls.source = icon.DEFAULT_SOURCE if setting == "1" else Path(setting)
        cls.source_data = cls.source.read_bytes()
        cls.source_mtime = cls.source.stat().st_mtime_ns
        cls.protected_fonts = {path: (icon.digest(path.read_bytes()), path.stat().st_mtime_ns)
                               for path in (ROOT / "build/font").glob("*.ttf")}
        cls.alpha, cls.record = icon.rasterize(cls.source_data)
        cls.license_data = (icon.DEFAULT_ARTIFACTS / icon.LICENSE_FILE).read_bytes()

    def test_actual_cmap_is_official_sports_esports(self):
        self.assertEqual(icon.digest(self.source_data), icon.SOURCE_SHA256)
        with TTFont(io.BytesIO(self.source_data), recalcTimestamp=False) as font:
            source = icon.validate_font(font)
            self.assertEqual(font.getBestCmap()[0xEA28], "sports_esports")
            self.assertEqual(source["family"], "Material Symbols Rounded")
            self.assertEqual(source["source_glyph_id"], 2018)
            self.assertEqual(source["source_units_per_em"], 960)
            for table in font["cmap"].tables:
                if table.isUnicode() and table.format in (4, 12):
                    table.cmap[0xEA28] = ".notdef"
            with self.assertRaisesRegex(icon.MaterialIconError, "actual cmap"):
                icon.validate_font(font)

    def test_source_with_conflicting_cmap_is_rejected(self):
        with TTFont(io.BytesIO(self.source_data), recalcTimestamp=False) as font:
            best = font.getBestCmap()
            other = next(table for table in font["cmap"].tables
                         if table.isUnicode() and table.format in (4, 12) and table.cmap is not best)
            # fontTools can share a dict between otherwise distinct subtables.
            other.cmap = dict(other.cmap)
            other.cmap[0xEA28] = ".notdef"
            with self.assertRaisesRegex(icon.MaterialIconError, "subtables disagree"):
                icon.validate_font(font)

    def test_header_alpha_png_manifest_and_license_match_regeneration(self):
        # This really reinstantiates the source font and reruns FreeType, offline.
        before = {path: (path.read_bytes(), path.stat().st_mtime_ns) for path in
                  [icon.DEFAULT_HEADER, *(icon.DEFAULT_ARTIFACTS / name for name in
                    (icon.ALPHA_FILE, icon.PNG_FILE, icon.MANIFEST_FILE, icon.LICENSE_FILE))]}
        with mock.patch.object(icon.urllib.request, "urlopen", side_effect=AssertionError("check must be offline")):
            checked = icon.build(self.source, check=True)
        manifest = json.loads((icon.DEFAULT_ARTIFACTS / icon.MANIFEST_FILE).read_bytes())
        self.assertEqual(checked, manifest)
        self.assertEqual(icon.render_header(self.alpha, self.record), icon.DEFAULT_HEADER.read_bytes())
        self.assertEqual(self.alpha, (icon.DEFAULT_ARTIFACTS / icon.ALPHA_FILE).read_bytes())
        self.assertEqual(read_header(icon.DEFAULT_HEADER.read_bytes())[1], self.alpha)
        with Image.open(icon.DEFAULT_ARTIFACTS / icon.PNG_FILE) as png:
            self.assertEqual(png.mode, "L")
            self.assertEqual(png.size, (60, 42))
            self.assertEqual(png.tobytes(), self.alpha)
        self.assertEqual(icon.digest(self.license_data), icon.LICENSE_SHA256)
        self.assertIn(b"Apache License", self.license_data)
        self.assertEqual(before, {path: (path.read_bytes(), path.stat().st_mtime_ns) for path in before})

    def test_repeatable_with_different_clock(self):
        with mock.patch("fontTools.ttLib.tables._h_e_a_d.timestampNow", return_value=4100000000):
            alpha, record = icon.rasterize(self.source_data)
        self.assertEqual(alpha, self.alpha)
        self.assertEqual(record, self.record)
        self.assertEqual(icon.render_header(alpha, record), icon.DEFAULT_HEADER.read_bytes())
        self.assertEqual(icon.digest(alpha), GOLDEN_ALPHA_SHA256)

    def test_check_detects_each_stale_output_without_repairing_it(self):
        # Publication/comparison fault injection reuses a genuinely rasterized
        # result, avoiding five redundant full-variable-font instantiations.
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            artifacts, header = root / "artifacts", root / "mix_game_icon.h"
            artifacts.mkdir()
            (artifacts / icon.LICENSE_FILE).write_bytes(self.license_data)
            with mock.patch.object(icon, "rasterize", side_effect=lambda data: (self.alpha, copy.deepcopy(self.record))):
                icon.build(self.source, header, artifacts)
                outputs = [header, artifacts / icon.ALPHA_FILE, artifacts / icon.PNG_FILE,
                           artifacts / icon.MANIFEST_FILE]
                for path in outputs:
                    original = path.read_bytes()
                    path.write_bytes(original + b"stale")
                    with self.subTest(output=path.name), self.assertRaisesRegex(icon.MaterialIconError, "differ"):
                        icon.build(self.source, header, artifacts, check=True)
                    self.assertEqual(path.read_bytes(), original + b"stale")
                    path.write_bytes(original)
                header.unlink()
                with self.assertRaisesRegex(icon.MaterialIconError, "missing"):
                    icon.build(self.source, header, artifacts, check=True)
                self.assertFalse(header.exists())

    def test_license_corruption_is_rejected(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            (root / icon.LICENSE_FILE).write_bytes(self.license_data + b"changed")
            with mock.patch.object(icon, "rasterize") as rasterize:
                with self.assertRaisesRegex(icon.MaterialIconError, "license SHA256 mismatch"):
                    icon.build(self.source, root / "icon.h", root, check=True)
                rasterize.assert_not_called()
            self.assertFalse((root / "icon.h").exists())

    def test_zz_existing_text_fonts_and_original_source_remain_unchanged(self):
        self.assertEqual(self.source.read_bytes(), self.source_data)
        self.assertEqual(self.source.stat().st_mtime_ns, self.source_mtime)
        self.assertEqual(self.protected_fonts, {
            path: (icon.digest(path.read_bytes()), path.stat().st_mtime_ns)
            for path in self.protected_fonts})


if __name__ == "__main__":
    unittest.main()
