# After project(): component manager has supplied a COMPLETE pristine dependency.
# Replace only ES8389 compilation unit; never edit managed dependency files.
set(_codec __idf_espressif__esp_codec_dev)
if(NOT TARGET ${_codec})
    message(FATAL_ERROR "MixOS requires registry esp_codec_dev 1.6.2")
endif()
get_target_property(_sources ${_codec} SOURCES)
set(_filtered "")
set(_found FALSE)
foreach(_src IN LISTS _sources)
    if(_src MATCHES "(^|/)es8389\\.c$")
        set(_found TRUE)
    else()
        list(APPEND _filtered "${_src}")
    endif()
endforeach()
if(NOT _found)
    message(FATAL_ERROR "ES8389 source missing; enable CONFIG_CODEC_ES8389_SUPPORT or check pinned dependency")
endif()
set_property(TARGET ${_codec} PROPERTY SOURCES "${_filtered}")
target_sources(${_codec} PRIVATE "${CMAKE_CURRENT_LIST_DIR}/codec_overlay/device/es8389/es8389.c")
target_include_directories(${_codec} BEFORE PUBLIC "${CMAKE_CURRENT_LIST_DIR}/codec_overlay/device/include")
target_include_directories(__idf_main BEFORE PRIVATE "${CMAKE_CURRENT_LIST_DIR}/codec_overlay/device/include")
