"""Pure, bounded binary evidence for one old ESP32-S3 bootloader.

This is a SEPARATE evidence type, never historical-build/config provenance and
never an approval issuer. No file, network, process or device access occurs.
The caller supplies original bytes from an externally operator-approved,
immutable package. The package must pin this implementation and ALL artifacts
in ARTIFACT_SHA256; authenticating that approval and enforcing package ownership,
immutability and task permissions remain the caller's responsibilities. A JSON
'reviewed' boolean, a report generated by this module, or successful validation
cannot replace those controls. No such approved package is created here.

Only the exact audited pair is accepted. Hashes authenticate artifact identity,
not the truth of arbitrary JSON: image structure, derived checksums, every
changed byte and the pinned full-function ranges are checked independently.
Human review of the pinned disassembly supplies the bounded semantic meaning.
There is no caller-supplied mask, alternate hash, arbitrary review or fallback.

Integration may use the result as ONE input to separately authorized current-A
no-flash-programming qualification, retaining recovery/migration identity,
full boot-region padding, partition/otadata/fallback identity, hardware/debug
state, communication, health, service/lock and reset controls. Current-A boot
success still needs observation. This module refuses B-install use. Such an
extension needs independent exact candidate bin/ELF/config/manifest review,
image/target/partition compatibility, safe receiver and confirmation contract,
and the complete OLD 9000ms pre-takeover budget with margin. An early app hook
cannot fix a deadline missed before the hook is reached.
"""
from __future__ import annotations

from collections.abc import Mapping
from dataclasses import dataclass, field
import hashlib
import json
import struct
from types import MappingProxyType


OLD_SHA256 = '6ea16d3717dbe339973b44109f4bd9bd50d6000418e58f677cd5b9e45116531d'
REFERENCE_SHA256 = '78648f9881f35dd593f7c42c75e0bf82c380c569ce1a4985618ef512a184ef2f'
REFERENCE_CONFIG_SHA256 = '62586acf011fd1810d6cb44161c4ff6924ec4982bf53520721251e2a9b269cc2'
QUALIFICATION_PURPOSE = 'qualify-current-a-no-write'
ROUTE = 'mixos-reviewed-bootloader-binary-evidence/v1'

# Fixed originals from the bounded 2026-09-16 local audit. Repinning is a code
# and operator review, NOT a runtime option or an automatic new approval.
ARTIFACT_SHA256 = MappingProxyType({
    'old_bootloader': OLD_SHA256,
    'reference_bootloader': REFERENCE_SHA256,
    'reference_config': REFERENCE_CONFIG_SHA256,
    'reference_elf': '07ed8215976c13f850cdb604097843579ff77f569ff4fe2f2f5ac193d7af9cc2',
    'bounded-recheck.json': '3c252cf99df1e07e9396165291a593aac775a2af5f227c0e9911994c011f0026',
    'audited-behavior.json': '0c1ee119f5441edbc102d5c3aa4b4758f9b4531adbc5d0ba60612d2f3744c304',
    'byte-comparison.json': 'b9303f56ea14fdd0789ea0bdc6dbc0d324748aa8ae4895fe13121d1a8057e4e5',
    'semantic-verification.json': '0529ddf544e65092751d0d5961b347c335cb95fc66820ae12a5ae6356fe708cd',
    'rollback-paths.json': '7170a1eebf5eb4f5f8fd18c0ee5e2e39a4c3b1202b0f0a23e32890bf796e702d',
    'startup-takeover.json': '14ffaa29031e827254acd9381e8760774b68874c157dc7fa225618d0a3a9295c',
})

_IMAGE_SIZE = 0x5220
_HEADER = bytes.fromhex('e904023f28893c40ee000000090000000063000000000001')
# (segment header file offset, load address, payload length). Exact mapping;
# there is deliberately no generic segment that can be ignored or normalized.
_SEGMENTS = (
    (0x18, 0x3FCE2810, 0x1564),
    (0x1584, 0x403C8700, 4),
    (0x1590, 0x403C8704, 0xD24),
    (0x22BC, 0x403CB700, 0x2F2C),
)
_CHECKSUM_AT = 0x51FF
_WDT_OFFSET = 0x1FAC
# File-order bytes, not objdump's little-endian displayed opcode integer.
_OLD_WDT = bytes.fromhex('0c9c')  # movi.n a12, 9
_REFERENCE_WDT = bytes.fromhex('1cec')  # movi.n a12, 30
_DIFFERENCE_RUNS = (
    (0x4D, b'3', b'6'),
    (0x55, b'0', b'6'),
    (0x57, b'54', b'32'),
    (0x5A, b'17', b'48'),
    (_WDT_OFFSET, _OLD_WDT, _REFERENCE_WDT),
    # These bytes must ALSO be independently derived from each entire image.
    (_CHECKSUM_AT,
     bytes.fromhex('3ec227c314d156771cf73df0bb86570da8b215d5e389579328b1298715ab837a80'),
     bytes.fromhex('577e7cd1ee6fe089defb343aca5a1da6fa776ca3b8ae3fea38744950061371947f')),
)
_REFERENCE_SETTINGS = MappingProxyType({
    'IDF_TARGET': 'esp32s3',
    'BOOTLOADER_APP_ROLLBACK_ENABLE': True,
    'BOOTLOADER_APP_ANTI_ROLLBACK': False,
    'BOOTLOADER_OFFSET_IN_FLASH': 0,
    'PARTITION_TABLE_OFFSET': 0x8000,
    'BOOTLOADER_REGION_PROTECTION_ENABLE': True,
    'BOOTLOADER_APP_TEST': False,
    'BOOTLOADER_FACTORY_RESET': False,
    'BOOTLOADER_SKIP_VALIDATE_ALWAYS': False,
    'BOOTLOADER_SKIP_VALIDATE_IN_DEEP_SLEEP': False,
    'BOOTLOADER_SKIP_VALIDATE_ON_POWER_ON': False,
    'BOOTLOADER_WDT_ENABLE': True,
    'BOOTLOADER_WDT_DISABLE_IN_USER_CODE': True,
    'BOOTLOADER_WDT_TIME_MS': 30000,
    'EFUSE_VIRTUAL': False,
    'SECURE_BOOT': False,
    'SECURE_FLASH_ENC_ENABLED': False,
    'SECURE_SIGNED_APPS_NO_SECURE_BOOT': False,
})

LIMITATIONS = (
    'Historical old sdkconfig/build provenance remains unknown.',
    'Whole bootloader behavior is not equivalent: banner and watchdog differ.',
    '9000ms is the old nominal RWDT setting, not measured physical expiry or available app time.',
    'Candidate startup timing, pre-takeover margin, compatibility and boot success are outside this evidence.',
    'Rollback code attempts NEW->PENDING_VERIFY and PENDING_VERIFY->ABORTED writes; persistence and power-loss safety are unproven.',
    'Ordinary loading selects validation mode; attached debugger may bypass checksum/SHA comparison and appended SHA is conditional.',
    'XOR and unkeyed SHA256 establish integrity, not secure-boot or publisher authentication.',
    'General partition fallback may retry a physical partition without filtering its prior OTA state.',
    'Installed bytes, chip/ROM/eFuse/debug state, live otadata, communication and application health are not measured.',
    'Current-A qualification still needs external immutable-package approval and all other trust gates; no B-install authorization.',
)


class EvidenceRefused(ValueError):
    """Evidence is absent, changed, out of scope or structurally invalid."""


def _require(condition, message):
    if not condition:
        raise EvidenceRefused(message)


def _sha(data):
    return hashlib.sha256(data).hexdigest()


def _json_object(data):
    def pairs(items):
        result = {}
        for key, value in items:
            _require(key not in result, 'Duplicate JSON field: ' + key)
            result[key] = value
        return result

    def invalid_constant(value):
        raise EvidenceRefused('Non-finite JSON constant: ' + value)

    try:
        result = json.loads(data, object_pairs_hook=pairs, parse_constant=invalid_constant)
    except (ValueError, UnicodeError, RecursionError) as exc:
        raise EvidenceRefused('Invalid evidence JSON: ' + str(exc)) from exc
    _require(type(result) is dict, 'Evidence JSON object required')
    return result


def _validate_image(data):
    """Strict parser for this reviewed four-segment layout, NOT identity proof."""
    _require(type(data) is bytes and len(data) == _IMAGE_SIZE,
             'Exact original 21024-byte bootloader image required; no trailing data')
    _require(data[:24] == _HEADER, 'Unreviewed ESP32-S3 image header')
    offset, checksum = 24, 0xEF
    loaded = []
    for expected_offset, expected_address, expected_size in _SEGMENTS:
        _require(offset == expected_offset and offset + 8 <= len(data), 'Invalid segment header position')
        address, size = struct.unpack_from('<II', data, offset)
        _require((address, size) == (expected_address, expected_size), 'Unreviewed segment layout')
        offset += 8
        _require(size > 0 and size % 4 == 0 and address % 4 == 0
                 and offset + size <= len(data) and address + size <= 0x100000000,
                 'Invalid segment size/address')
        _require(not any(address < end and start < address + size for start, end in loaded),
                 'Overlapping load segments')
        loaded.append((address, address + size))
        for byte in data[offset:offset + size]:
            checksum ^= byte
        offset += size
    entry = struct.unpack_from('<I', data, 4)[0]
    _require(any(start <= entry < end for start, end in loaded[1:]), 'Entry outside executable segment')
    checksum_at = offset | 15
    _require(checksum_at == _CHECKSUM_AT and checksum_at + 33 == len(data), 'Invalid checksum layout')
    _require(not any(data[offset:checksum_at]), 'Nonzero image padding')
    _require(data[checksum_at] == checksum, 'ESP image XOR checksum mismatch')
    _require(data[checksum_at + 1:] == hashlib.sha256(data[:checksum_at + 1]).digest(),
             'Appended image SHA256 mismatch')


def _validate_pair(old, reference):
    _validate_image(old)
    _validate_image(reference)
    _require(old[_WDT_OFFSET:_WDT_OFFSET + 2] == _OLD_WDT
             and reference[_WDT_OFFSET:_WDT_OFFSET + 2] == _REFERENCE_WDT,
             'Original watchdog instruction at 0x1fac must be 0c9c / 1cec')
    expected_offsets = frozenset(offset + i for offset, before, _ in _DIFFERENCE_RUNS
                                 for i in range(len(before)))
    actual_offsets = frozenset(i for i, (a, b) in enumerate(zip(old, reference)) if a != b)
    _require(actual_offsets == expected_offsets, 'Unspecified or missing bootloader byte differences')
    for offset, before, after in _DIFFERENCE_RUNS:
        _require(old[offset:offset + len(before)] == before
                 and reference[offset:offset + len(after)] == after,
                 'Original difference bytes mismatch at ' + hex(offset))


def _validate_reference_config(data):
    config = _json_object(data)
    for name, expected in _REFERENCE_SETTINGS.items():
        value = config.get(name)
        _require(type(value) is type(expected) and value == expected,
                 'Reference safety setting mismatch: ' + name)
    # These are current reference settings only. They are never labeled old
    # Kconfig or used to replace the old machine-code 9000ms watchdog budget.


def _recheck_functions(report, old, reference):
    """Recompute complete ranges; semantic/call-graph review remains external."""
    functions = report.get('full_functions_rechecked')
    _require(type(functions) is list and len(functions) == 48, 'Expected 48 reviewed full functions')
    names, changed = set(), []
    for function in functions:
        name = function['name']
        _require(name not in names, 'Duplicate reviewed function')
        names.add(name)
        start = function['binary_range']['start']
        end = function['binary_range']['end_exclusive']
        _require(type(start) is int and type(end) is int and 0 <= start < end <= _CHECKSUM_AT,
                 'Invalid reviewed function range')
        a, b = old[start:end], reference[start:end]
        _require(_sha(a) == function['old_sha256'] and _sha(b) == function['current_sha256'],
                 'Reviewed function bytes mismatch: ' + name)
        _require(function['old_current_equal'] is (a == b), 'Function equality assertion mismatch')
        if a != b:
            changed.append(name)
    _require(changed == ['bootloader_config_wdt'], 'Only the reviewed watchdog function may differ')
    _require({'call_start_cpu0', 'bootloader_utility_get_selected_boot_partition',
              'write_otadata$isra$0', 'bootloader_load_image', 'image_load'} <= names,
             'Missing reviewed rollback/ordinary-validation functions')


@dataclass(frozen=True)
class BinaryEvidence:
    """Bounded static findings, not a capability token or deployment permission."""
    old_sha256: str
    reference_sha256: str
    reference_config_sha256: str
    old_boot_region_sha256: str
    artifact_hashes: tuple[tuple[str, str], ...]
    route: str = field(default=ROUTE, init=False)
    use: str = field(default=QUALIFICATION_PURPOSE, init=False)
    old_nominal_startup_watchdog_ms: int = field(default=9000, init=False)
    reference_nominal_startup_watchdog_ms: int = field(default=30000, init=False)
    equal_reviewed_full_functions: int = field(default=47, init=False)
    reviewed_full_functions: int = field(default=48, init=False)
    deployment_authorized: bool = field(default=False, init=False)
    historical_config_recovered: bool = field(default=False, init=False)
    whole_behavior_equivalent: bool = field(default=False, init=False)
    candidate_compatibility_proven: bool = field(default=False, init=False)
    static_findings: tuple[str, ...] = field(default=(
        'Exact old binary implements reachable NEW->PENDING_VERIFY and PENDING_VERIFY->ABORTED transitions.',
        'Ordinary selected/fallback app-loading paths select ESP_IMAGE_LOAD=2 validation mode.',
        '47 of 48 reviewed complete function ranges match; watchdog function differs at the fixed instruction.',
    ), init=False)
    limitations: tuple[str, ...] = field(default=LIMITATIONS, init=False)


def validate_reviewed_binary_evidence(artifacts: Mapping[str, bytes], *, purpose: str) -> BinaryEvidence:
    """Validate original artifacts without effects; return evidence, NOT approval.

    Exactly ARTIFACT_SHA256's keys and immutable bytes are required, including
    all six original audit reports and the reference ELF. No 'reviewed' flag or
    caller-chosen digest is accepted. All pins apply before JSON is interpreted.
    External operator authorization/immutable packaging cannot be established
    by this pure function and must precede any integrated device operation.
    """
    _require(purpose == QUALIFICATION_PURPOSE,
             'Only current-A no-write qualification evidence; B install requires a separate candidate compatibility gate')
    _require(isinstance(artifacts, Mapping), 'Artifact byte mapping required')
    files = dict(artifacts)
    _require(set(files) == set(ARTIFACT_SHA256), 'Exact pinned artifact set required; missing review or unexpected artifact')
    for name, expected in ARTIFACT_SHA256.items():
        data = files[name]
        _require(type(data) is bytes and 0 < len(data) <= 2 * 1024 * 1024,
                 'Original bounded artifact bytes required: ' + name)
        _require(_sha(data) == expected, 'Pinned artifact SHA256 mismatch: ' + name)
    old, reference = files['old_bootloader'], files['reference_bootloader']
    _validate_pair(old, reference)
    _validate_reference_config(files['reference_config'])
    bounded = _json_object(files['bounded-recheck.json'])
    _recheck_functions(bounded, old, reference)
    # Preserve the reviewed negative claims rather than turning them into an
    # unconditional equivalence/security/persistence or deployment assertion.
    expected_verdict = {
        'old_rollback_implementation_present_and_reachable': True,
        'old_ordinary_app_loader_selects_validation_mode': True,
        'unconditional_all_states_full_validation_claim': False,
        'whole_bootloader_behavior_equivalent': False,
        'historical_sdkconfig_recovered': False,
        'runtime_rollback_qualified': False,
        'earlyhook_candidate_qualified': False,
        'deployment_authorized': False,
    }
    for report in (bounded, _json_object(files['audited-behavior.json'])):
        _require(report.get('verdict') == expected_verdict, 'Bounded audit scope changed')
    semantic = _json_object(files['semantic-verification.json'])['wdt_function']
    _require(semantic['old_file_order_bytes'] == _OLD_WDT.hex()
             and semantic['current_file_order_bytes'] == _REFERENCE_WDT.hex()
             and semantic['nominal_old_timeout_ms'] == 9000
             and semantic['nominal_current_timeout_ms'] == 30000,
             'Reviewed watchdog interpretation changed')
    return BinaryEvidence(OLD_SHA256, REFERENCE_SHA256, REFERENCE_CONFIG_SHA256,
                          _sha(old.ljust(0x8000, b'\xff')),
                          tuple(sorted(ARTIFACT_SHA256.items())))
